export const PERMISSIONS = {
  // User Management
  USER: {
    VIEW: 'VIEW_USER',
    ADD: 'ADD_USER',
    UPDATE: 'UPDATE_USER',
    DELETE: 'DELETE_USER',
    MANAGE_PERMISSION: 'MANAGE_USER_PERMISSION',
    CHANGE_POSITION: 'CHANGE_USER_POSITION',
  },

  // Position Management
  POSITION: {
    VIEW: 'VIEW_POSITION',
    ADD: 'ADD_POSITION',
    UPDATE: 'UPDATE_POSITION',
    DELETE: 'DELETE_POSITION',
  },

  // Permission Management
  PERMISSION: {
    VIEW: 'VIEW_PERMISSION',
    ADD: 'ADD_PERMISSION',
    UPDATE: 'UPDATE_PERMISSION',
    DELETE: 'DELETE_PERMISSION',
  },

  DISTRICT : {
    VIEW: 'VIEW_DISTRICT',
    ADD: 'ADD_DISTRICT',
    UPDATE: 'UPDATE_DISTRICT',
    DELETE: 'DELETE_DISTRICT',
  },

  PLACE: {
    VIEW: 'VIEW_PLACE',
    ADD: 'ADD_PLACE',
    UPDATE: 'UPDATE_PLACE',
    DELETE: 'DELETE_PLACE',
  },

  LAYER: {
    VIEW: 'VIEW_LAYER',
    ADD: 'ADD_LAYER',
    UPDATE: 'UPDATE_LAYER',
    DELETE: 'DELETE_LAYER',
  },
} as const;
